import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import {
  updateReactTierBarrel,
  updateReactRootBarrel,
  updateWCBarrel,
  updateWCRootBarrel,
  updateVueTierBarrel,
  updateVueRootBarrel,
  updateSvelteTierBarrel,
  updateSvelteRootBarrel,
  updateAngularTierBarrel,
  updateAngularRootBarrel,
  updateSolidTierBarrel,
  updateSolidRootBarrel,
  updatePreactTierBarrel,
  updatePreactRootBarrel,
  pruneBarrels,
} from '../src/generators/barrel.js';

const meta = {
  tag: 'arc-button',
  className: 'ArcButton',
  pascalName: 'Button',
  tier: 'reactive',
  props: [],
  css: '',
  template: '',
  events: [],
  interactivity: 'static',
  hostDisplay: 'block',
};

let tmpDir;

beforeEach(() => {
  tmpDir = mkdtempSync(join(tmpdir(), 'prism-barrel-'));
});

afterEach(() => {
  rmSync(tmpDir, { recursive: true, force: true });
});

// ── React ────────────────────────────────────────────────────

describe('React tier barrel', () => {
  it('appends export to existing tier barrel', () => {
    const tierDir = join(tmpDir, 'reactive');
    mkdirSync(tierDir, { recursive: true });
    writeFileSync(join(tierDir, 'index.ts'), '// existing\n');

    const result = updateReactTierBarrel(meta, tmpDir);
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tierDir, 'index.ts'), 'utf-8');
    expect(content).toContain("export { Button } from './Button.js'");
    expect(content).toContain("export type { ButtonProps } from './Button.js'");
  });

  it('skips duplicate exports', () => {
    const tierDir = join(tmpDir, 'reactive');
    mkdirSync(tierDir, { recursive: true });
    writeFileSync(
      join(tierDir, 'index.ts'),
      "export { Button } from './Button.js';\nexport type { ButtonProps } from './Button.js';\n",
    );

    const result = updateReactTierBarrel(meta, tmpDir);
    expect(result.updated).toBe(false);
  });

  it('creates the barrel (and its directory) when missing', () => {
    const result = updateReactTierBarrel(meta, tmpDir);
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tmpDir, 'reactive', 'index.ts'), 'utf-8');
    expect(content).toContain('Auto-generated by @arclux/prism');
    expect(content).toContain("export { Button } from './Button.js'");
  });

  it('does NOT treat a substring-name collision as a duplicate', () => {
    // Regression: `Button` used to substring-match inside an existing
    // `IconButton` export and get silently dropped.
    const tierDir = join(tmpDir, 'reactive');
    mkdirSync(tierDir, { recursive: true });
    writeFileSync(
      join(tierDir, 'index.ts'),
      "export { IconButton } from './IconButton.js';\n" +
        "export type { IconButtonProps } from './IconButton.js';\n",
    );

    const result = updateReactTierBarrel(meta, tmpDir); // meta.pascalName === 'Button'
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tierDir, 'index.ts'), 'utf-8');
    expect(content).toContain("export { Button } from './Button.js'");
  });

  it('still skips a genuine whole-word duplicate', () => {
    const tierDir = join(tmpDir, 'reactive');
    mkdirSync(tierDir, { recursive: true });
    writeFileSync(
      join(tierDir, 'index.ts'),
      "export { Button } from './Button.js';\nexport type { ButtonProps } from './Button.js';\n",
    );
    const result = updateReactTierBarrel(meta, tmpDir);
    expect(result.updated).toBe(false);
  });
});

describe('React root barrel', () => {
  it('appends export lines to root barrel', () => {
    writeFileSync(join(tmpDir, 'index.ts'), '// root barrel\n');

    const result = updateReactRootBarrel(meta, tmpDir);
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tmpDir, 'index.ts'), 'utf-8');
    expect(content).toContain("export { Button } from './reactive/Button.js'");
    expect(content).toContain("export type { ButtonProps } from './reactive/Button.js'");
  });
});

// ── WC ───────────────────────────────────────────────────────

describe('WC tier barrel', () => {
  it('appends export to existing tier barrel', () => {
    const tierDir = join(tmpDir, 'reactive');
    mkdirSync(tierDir, { recursive: true });
    writeFileSync(join(tierDir, 'index.js'), '// existing\n');

    const result = updateWCBarrel(meta, tmpDir);
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tierDir, 'index.js'), 'utf-8');
    expect(content).toContain("export { ArcButton } from './button.js'");
  });
});

describe('WC root barrel — merge strategy', () => {
  it('merges into existing tier export line', () => {
    writeFileSync(
      join(tmpDir, 'index.js'),
      "export { ArcCard } from './reactive/index.js';\n",
    );

    const result = updateWCRootBarrel(meta, tmpDir);
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tmpDir, 'index.js'), 'utf-8');
    expect(content).toContain('ArcCard');
    expect(content).toContain('ArcButton');
    expect(content).toContain("from './reactive/index.js'");
  });

  it('appends new line when no existing tier export', () => {
    writeFileSync(join(tmpDir, 'index.js'), '// root\n');

    const result = updateWCRootBarrel(meta, tmpDir);
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tmpDir, 'index.js'), 'utf-8');
    expect(content).toContain('ArcButton');
    expect(content).toContain("from './reactive/index.js'");
  });
});

// ── Vue ──────────────────────────────────────────────────────

describe('Vue tier barrel', () => {
  it('appends default-as export to tier barrel', () => {
    const tierDir = join(tmpDir, 'reactive');
    mkdirSync(tierDir, { recursive: true });
    writeFileSync(join(tierDir, 'index.ts'), '// existing\n');

    const result = updateVueTierBarrel(meta, tmpDir);
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tierDir, 'index.ts'), 'utf-8');
    expect(content).toContain("export { default as Button } from './Button.vue'");
  });

  it('skips duplicates', () => {
    const tierDir = join(tmpDir, 'reactive');
    mkdirSync(tierDir, { recursive: true });
    writeFileSync(join(tierDir, 'index.ts'), "export { default as Button } from './Button.vue';\n");

    const result = updateVueTierBarrel(meta, tmpDir);
    expect(result.updated).toBe(false);
  });
});

describe('Vue root barrel', () => {
  it('appends export to root barrel', () => {
    writeFileSync(join(tmpDir, 'index.ts'), '// root\n');

    const result = updateVueRootBarrel(meta, tmpDir);
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tmpDir, 'index.ts'), 'utf-8');
    expect(content).toContain("export { default as Button } from './reactive/Button.vue'");
  });
});

// ── Svelte ───────────────────────────────────────────────────

describe('Svelte tier barrel', () => {
  it('appends default-as export to tier barrel', () => {
    const tierDir = join(tmpDir, 'reactive');
    mkdirSync(tierDir, { recursive: true });
    writeFileSync(join(tierDir, 'index.ts'), '// existing\n');

    const result = updateSvelteTierBarrel(meta, tmpDir);
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tierDir, 'index.ts'), 'utf-8');
    expect(content).toContain("export { default as Button } from './Button.svelte'");
  });
});

describe('Svelte root barrel', () => {
  it('appends export to root barrel', () => {
    writeFileSync(join(tmpDir, 'index.ts'), '// root\n');

    const result = updateSvelteRootBarrel(meta, tmpDir);
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tmpDir, 'index.ts'), 'utf-8');
    expect(content).toContain("export { default as Button } from './reactive/Button.svelte'");
  });
});

// ── Angular ──────────────────────────────────────────────────

describe('Angular tier barrel', () => {
  it('appends named export to tier barrel', () => {
    const tierDir = join(tmpDir, 'reactive');
    mkdirSync(tierDir, { recursive: true });
    writeFileSync(join(tierDir, 'index.ts'), '// existing\n');

    const result = updateAngularTierBarrel(meta, tmpDir);
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tierDir, 'index.ts'), 'utf-8');
    // Extensionless: ngc emits .mjs keeping specifiers verbatim, so a '.js'
    // suffix breaks ng-packagr's flatten step.
    expect(content).toContain("export { Button } from './Button';");
    // Angular doesn't export types separately
    expect(content).not.toContain('ButtonProps');
  });
});

describe('Angular root barrel', () => {
  it('appends export to root barrel', () => {
    writeFileSync(join(tmpDir, 'index.ts'), '// root\n');

    const result = updateAngularRootBarrel(meta, tmpDir);
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tmpDir, 'index.ts'), 'utf-8');
    expect(content).toContain("export { Button } from './reactive/Button';");
  });
});

// ── Solid ────────────────────────────────────────────────────

describe('Solid tier barrel', () => {
  it('appends export + type export to tier barrel', () => {
    const tierDir = join(tmpDir, 'reactive');
    mkdirSync(tierDir, { recursive: true });
    writeFileSync(join(tierDir, 'index.ts'), '// existing\n');

    const result = updateSolidTierBarrel(meta, tmpDir);
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tierDir, 'index.ts'), 'utf-8');
    expect(content).toContain("export { Button } from './Button.js'");
    expect(content).toContain("export type { ButtonProps } from './Button.js'");
  });
});

describe('Solid root barrel', () => {
  it('appends export to root barrel', () => {
    writeFileSync(join(tmpDir, 'index.ts'), '// root\n');

    const result = updateSolidRootBarrel(meta, tmpDir);
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tmpDir, 'index.ts'), 'utf-8');
    expect(content).toContain("export { Button } from './reactive/Button.js'");
    expect(content).toContain("export type { ButtonProps } from './reactive/Button.js'");
  });
});

// ── Preact ───────────────────────────────────────────────────

describe('Preact tier barrel', () => {
  it('appends export + type export to tier barrel', () => {
    const tierDir = join(tmpDir, 'reactive');
    mkdirSync(tierDir, { recursive: true });
    writeFileSync(join(tierDir, 'index.ts'), '// existing\n');

    const result = updatePreactTierBarrel(meta, tmpDir);
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tierDir, 'index.ts'), 'utf-8');
    expect(content).toContain("export { Button } from './Button.js'");
    expect(content).toContain("export type { ButtonProps } from './Button.js'");
  });
});

describe('Preact root barrel', () => {
  it('appends export to root barrel', () => {
    writeFileSync(join(tmpDir, 'index.ts'), '// root\n');

    const result = updatePreactRootBarrel(meta, tmpDir);
    expect(result.updated).toBe(true);
    const content = readFileSync(join(tmpDir, 'index.ts'), 'utf-8');
    expect(content).toContain("export { Button } from './reactive/Button.js'");
    expect(content).toContain("export type { ButtonProps } from './reactive/Button.js'");
  });
});

describe('pruneBarrels: a removed component stops being exported', () => {
  let dir;

  const button = { tag: 'arc-button', className: 'ArcButton', pascalName: 'Button', tier: 'input' };
  const toast = { tag: 'arc-toast', className: 'ArcToast', pascalName: 'Toast', tier: 'feedback' };
  const manager = {
    tag: 'arc-toast-manager', className: 'ArcToastManager',
    pascalName: 'ToastManager', tier: 'feedback',
  };

  const config = () => ({
    prefix: 'arc',
    tiers: ['input', 'feedback'],
    components: 'wc',
    react: { outDir: 'react', barrels: true },
  });

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'prism-prune-'));
    for (const tier of ['input', 'feedback']) {
      mkdirSync(join(dir, 'wc', tier), { recursive: true });
      mkdirSync(join(dir, 'react', tier), { recursive: true });
    }
  });
  afterEach(() => rmSync(dir, { recursive: true, force: true }));

  /**
   * Reproduce the state the append-only path leaves behind: barrels exporting
   * every component, and files on disk for only the ones that still exist.
   */
  function seed(all, present = all) {
    for (const m of all) {
      updateWCBarrel(m, join(dir, 'wc'), 'arc');
      updateWCRootBarrel(m, join(dir, 'wc'));
      updateReactTierBarrel(m, join(dir, 'react'));
      updateReactRootBarrel(m, join(dir, 'react'));
    }
    for (const m of present) {
      const wcFile = m.tag.replace(/^arc-/, '');
      writeFileSync(join(dir, 'wc', m.tier, `${wcFile}.js`), '// component\n');
      writeFileSync(join(dir, 'react', m.tier, `${m.pascalName}.ts`), '// wrapper\n');
    }
  }

  const read = (...parts) => readFileSync(join(dir, ...parts), 'utf-8');

  it('drops a tier-barrel export whose file is gone', () => {
    seed([toast, manager], [toast]);
    expect(read('react', 'feedback', 'index.ts')).toContain('ToastManager');

    pruneBarrels(config(), dir);

    const barrel = read('react', 'feedback', 'index.ts');
    expect(barrel).not.toContain('ToastManager');
    expect(barrel, 'the surviving component is untouched').toContain("from './Toast.js'");
  });

  it('resolves a .js specifier to its .ts file rather than calling it broken', () => {
    // The wrapper is Toast.ts; the barrel says './Toast.js'. Treating that as
    // unresolvable would delete every working export in the package.
    seed([toast], [toast]);
    const before = read('react', 'feedback', 'index.ts');
    expect(pruneBarrels(config(), dir)).toEqual([]);
    expect(read('react', 'feedback', 'index.ts')).toBe(before);
  });

  it('drops the matching type export too', () => {
    seed([toast, manager], [toast]);
    pruneBarrels(config(), dir);
    const barrel = read('react', 'feedback', 'index.ts');
    expect(barrel).not.toContain('ToastManagerProps');
    expect(barrel).toContain('ToastProps');
  });

  it('drops a root-barrel export whose tier-qualified file is gone', () => {
    seed([toast, manager], [toast]);
    expect(read('react', 'index.ts')).toContain('feedback/ToastManager.js');

    pruneBarrels(config(), dir);
    expect(read('react', 'index.ts')).not.toContain('ToastManager');
  });

  it('filters identifiers out of a barrel-to-barrel re-export', () => {
    // The WC root barrel re-exports whole tier barrels, so the path resolves
    // either way — only the identifier list can reveal the removal.
    seed([toast, manager], [toast]);
    expect(read('wc', 'index.js')).toContain('ArcToastManager');

    pruneBarrels(config(), dir);

    const after = read('wc', 'index.js');
    expect(after).not.toContain('ArcToastManager');
    expect(after, 'the tier re-export survives with its live names').toContain('ArcToast');
    expect(after).toContain("from './feedback/index.js'");
  });

  it('removes a re-export line once none of its names survive', () => {
    seed([manager], []);
    pruneBarrels(config(), dir);
    expect(read('wc', 'index.js')).not.toContain('feedback/index.js');
  });

  it('leaves a barrel with nothing stale completely alone', () => {
    seed([button, toast]);
    const before = {
      wc: read('wc', 'index.js'),
      react: read('react', 'index.ts'),
      tier: read('react', 'feedback', 'index.ts'),
    };

    expect(pruneBarrels(config(), dir), 'reports no change').toEqual([]);

    expect(read('wc', 'index.js')).toBe(before.wc);
    expect(read('react', 'index.ts')).toBe(before.react);
    expect(read('react', 'feedback', 'index.ts')).toBe(before.tier);
  });

  it('never judges an export by its naming convention', () => {
    // Regression guard for the first version of this pass, which rebuilt the
    // expected specifiers from the metas and stripped 136 working exports from a
    // project whose barrels point at './accordion.register.js' — a filename this
    // generator would never write, in a barrel it does not generate.
    writeFileSync(join(dir, 'wc', 'input', 'button.register.js'), '// registration\n');
    writeFileSync(
      join(dir, 'wc', 'input', 'index.js'),
      "// Auto-generated by @arclux/prism — do not edit manually\n"
      + "export { ArcButton } from './button.register.js';\n",
    );

    expect(pruneBarrels(config(), dir)).toEqual([]);
    expect(read('wc', 'input', 'index.js')).toContain('button.register.js');
  });

  it('keeps the generated header', () => {
    seed([toast, manager], [toast]);
    pruneBarrels(config(), dir);
    expect(read('react', 'feedback', 'index.ts'))
      .toContain('Auto-generated by @arclux/prism');
  });

  it('reports what it removed, per barrel', () => {
    seed([toast, manager], [toast]);
    const changed = pruneBarrels(config(), dir);

    expect(changed.length).toBeGreaterThan(0);
    const all = changed.flatMap((c) => c.removed);
    expect(all.some((n) => /ToastManager/.test(n))).toBe(true);
    expect(all.some((n) => n === 'Toast'), 'never the survivor').toBe(false);
  });

  it('does not touch a framework whose barrels are disabled', () => {
    seed([toast, manager], [toast]);
    const cfg = config();
    cfg.react.barrels = false;
    const before = read('react', 'feedback', 'index.ts');

    pruneBarrels(cfg, dir);
    expect(read('react', 'feedback', 'index.ts')).toBe(before);
  });
});

describe('pruneBarrels: output hygiene', () => {
  let dir;
  const toast = { tag: 'arc-toast', className: 'ArcToast', pascalName: 'Toast', tier: 'feedback' };

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'prism-prune-ws-'));
    mkdirSync(join(dir, 'react', 'feedback'), { recursive: true });
  });
  afterEach(() => rmSync(dir, { recursive: true, force: true }));

  it('leaves no trailing blank line behind', () => {
    // A prune that changes whitespace shows up in a consumer's diff as noise and
    // makes a generate-diff CI gate fail for no real reason.
    const barrel = join(dir, 'react', 'feedback', 'index.ts');
    writeFileSync(
      barrel,
      "// Auto-generated by @arclux/prism — do not edit manually\n\n"
      + "export { Toast } from './Toast.js';\n"
      + "export { Gone } from './Gone.js';\n",
    );
    writeFileSync(join(dir, 'react', 'feedback', 'Toast.ts'), '// wrapper\n');

    pruneBarrels({ prefix: 'arc', tiers: ['feedback'], react: { outDir: 'react', barrels: true } }, dir);

    const after = readFileSync(barrel, 'utf-8');
    expect(after.endsWith("from './Toast.js';\n")).toBe(true);
    expect(after).not.toMatch(/\n\n$/);
    void toast;
  });
});

describe('barrelExclude: a component kept out of the barrels', () => {
  let dir;

  const toast = { tag: 'arc-toast', className: 'ArcToast', pascalName: 'Toast', tier: 'feedback' };
  const code = {
    tag: 'arc-code-block', className: 'ArcCodeBlock',
    pascalName: 'CodeBlock', tier: 'typography',
  };

  const config = () => ({
    prefix: 'arc',
    tiers: ['feedback', 'typography'],
    components: 'wc',
    react: { outDir: 'react', barrels: true },
    barrelExclude: ['arc-code-block'],
  });

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'prism-bx-'));
    for (const tier of ['feedback', 'typography']) {
      mkdirSync(join(dir, 'wc', tier), { recursive: true });
      mkdirSync(join(dir, 'react', tier), { recursive: true });
    }
    // Both components exist on disk — exclusion is not about a missing file.
    for (const m of [toast, code]) {
      updateWCBarrel(m, join(dir, 'wc'), 'arc');
      updateWCRootBarrel(m, join(dir, 'wc'));
      updateReactTierBarrel(m, join(dir, 'react'));
      updateReactRootBarrel(m, join(dir, 'react'));
      writeFileSync(join(dir, 'wc', m.tier, `${m.tag.replace(/^arc-/, '')}.js`), '// component\n');
      writeFileSync(join(dir, 'react', m.tier, `${m.pascalName}.ts`), '// wrapper\n');
    }
  });
  afterEach(() => rmSync(dir, { recursive: true, force: true }));

  const read = (...parts) => readFileSync(join(dir, ...parts), 'utf-8');

  it('is removed from its tier barrel even though its file is right there', () => {
    expect(read('react', 'typography', 'index.ts')).toContain('CodeBlock');

    pruneBarrels(config(), dir, [toast, code]);

    expect(read('react', 'typography', 'index.ts')).not.toContain('CodeBlock');
  });

  it('is removed from the root barrel too', () => {
    pruneBarrels(config(), dir, [toast, code]);
    expect(read('react', 'index.ts')).not.toContain('CodeBlock');
    expect(read('wc', 'index.js')).not.toContain('ArcCodeBlock');
  });

  it('leaves every other component alone', () => {
    pruneBarrels(config(), dir, [toast, code]);
    expect(read('react', 'feedback', 'index.ts')).toContain('Toast');
    expect(read('react', 'index.ts')).toContain('Toast');
    expect(read('wc', 'index.js')).toContain('ArcToast');
  });

  it('does nothing without the config entry', () => {
    pruneBarrels({ ...config(), barrelExclude: [] }, dir, [toast, code]);
    expect(read('react', 'typography', 'index.ts')).toContain('CodeBlock');
  });

  it('needs the meta, not a guess at the name', () => {
    // Names come from the metas, so a component whose meta this run never saw
    // is left alone rather than removed by a derived-from-the-tag guess.
    pruneBarrels(config(), dir, []);
    expect(read('react', 'typography', 'index.ts')).toContain('CodeBlock');
  });
});
