/**
 * The sentinel, and the version stamped into it.
 *
 * The version exists because an older prism does not fail — it reverts. What is
 * being protected here is both halves of that: that a downgrade is *detected*,
 * and that adding the stamp did not turn every file written before it into a
 * file prism refuses to touch. The second half is the one that would have been
 * a disaster: a sentinel that insisted on a version would have classified the
 * entire installed base as hand-edited and silently stopped regenerating it.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import {
  VERSION, HEADER, isPrismGenerated, generatedVersion, newerVersionIn,
  compareVersions, claimOutput,
} from '../src/generators/header.js';
import { generateReact } from '../src/generators/react.js';
import { scanForNewerOutput, describeDowngrade } from '../src/preflight.js';

let tmpDir;
beforeEach(() => { tmpDir = mkdtempSync(join(tmpdir(), 'prism-header-')); });
afterEach(() => { rmSync(tmpDir, { recursive: true, force: true }); });

const meta = {
  tag: 'arc-button',
  className: 'ArcButton',
  pascalName: 'Button',
  tier: 'reactive',
  props: [],
  css: '',
  template: '<button><slot></slot></button>',
  events: [],
  hasDefaultSlot: true,
  interactivity: 'static',
};
const config = { outDir: 'out', wcPackage: '@arclux/arc-ui', prefix: 'arc', barrels: false };

describe('the generated-file sentinel', () => {
  it('carries the running version', () => {
    expect(HEADER).toContain(`@arclux/prism ${VERSION}`);
    expect(generatedVersion(HEADER)).toBe(VERSION);
  });

  it('still recognises output written before versions were stamped', () => {
    const old = '// Auto-generated by @arclux/prism — do not edit manually\n\nexport const x = 1;';
    expect(isPrismGenerated(old)).toBe(true);
    expect(generatedVersion(old)).toBe(null);
  });

  it('still recognises output written under the old org name', () => {
    const renamed = '// Auto-generated by @arclight/prism 2.4.0 — do not edit manually';
    expect(isPrismGenerated(renamed)).toBe(true);
    expect(generatedVersion(renamed)).toBe('2.4.0');
  });

  it('does not claim a hand-written file', () => {
    expect(isPrismGenerated('// hand-rolled, please keep\nexport const x = 1;')).toBe(false);
  });

  it('only inspects the head of the file, so prose cannot impersonate it', () => {
    const prose = `${'\n'.repeat(400)}Auto-generated by @arclux/prism 3.0.0 — do not edit manually`;
    expect(isPrismGenerated(prose)).toBe(false);
  });
});

describe('compareVersions', () => {
  it('orders by numeric segment, not lexically', () => {
    expect(compareVersions('2.10.0', '2.9.0')).toBeGreaterThan(0);
    expect(compareVersions('2.9.0', '2.10.0')).toBeLessThan(0);
    expect(compareVersions('3.0.0', '3.0.0')).toBe(0);
  });

  it('sorts a prerelease below its release', () => {
    expect(compareVersions('3.0.0-rc.1', '3.0.0')).toBeLessThan(0);
    expect(compareVersions('3.0.0', '3.0.0-rc.1')).toBeGreaterThan(0);
  });

  it('tolerates a missing segment', () => {
    expect(compareVersions('3.1', '3.0.9')).toBeGreaterThan(0);
  });
});

describe('claimOutput', () => {
  it('claims a path nothing occupies', () => {
    expect(claimOutput(join(tmpDir, 'nothing.ts'))).toEqual({ ours: true, priorVersion: null });
  });

  it('refuses a hand-written file at a generated path', () => {
    const path = join(tmpDir, 'Manual.ts');
    writeFileSync(path, 'export const Manual = 1;\n');
    expect(claimOutput(path).ours).toBe(false);
  });

  it('says nothing about output from this version or an older one', () => {
    const path = join(tmpDir, 'Old.ts');
    writeFileSync(path, '// Auto-generated by @arclux/prism 1.0.0 — do not edit manually\n');
    expect(claimOutput(path)).toEqual({ ours: true, priorVersion: null });
  });

  it('reports output written by a newer prism, which this run is about to revert', () => {
    const path = join(tmpDir, 'New.ts');
    writeFileSync(path, '// Auto-generated by @arclux/prism 99.0.0 — do not edit manually\n');
    expect(claimOutput(path).priorVersion).toBe('99.0.0');
  });
});

describe('newerVersionIn', () => {
  it('is null for the version doing the asking', () => {
    expect(newerVersionIn(HEADER)).toBe(null);
  });
});

describe('the pre-flight scan', () => {
  const config = (extra = {}) => ({
    tiers: ['reactive', 'content'],
    react: { outDir: 'packages/react/src' },
    ...extra,
  });

  /** Write a generated file with a given stamp. */
  const stamp = (rel, version) => {
    const path = join(tmpDir, rel);
    mkdirSync(join(path, '..'), { recursive: true });
    writeFileSync(path, version
      ? `// Auto-generated by @arclux/prism ${version} — do not edit manually\n\nexport const x = 1;\n`
      : '// Auto-generated by @arclux/prism — do not edit manually\n\nexport const x = 1;\n');
    return path;
  };

  it('finds nothing in an empty tree', () => {
    expect(scanForNewerOutput(config(), tmpDir).newer).toEqual([]);
  });

  it('says nothing about output from this version or older', () => {
    stamp('packages/react/src/reactive/Button.ts', VERSION);
    stamp('packages/react/src/content/Card.ts', '1.0.0');
    const scan = scanForNewerOutput(config(), tmpDir);
    expect(scan.newer).toEqual([]);
    // Both were read and recognised — the check ran, it just had nothing to say.
    expect(scan.scanned).toBe(2);
  });

  it('says nothing about output written before versions were stamped', () => {
    // Every file in the installed base is unstamped. Treating those as suspect
    // would make the first run after upgrading refuse to do anything.
    stamp('packages/react/src/reactive/Button.ts', null);
    expect(scanForNewerOutput(config(), tmpDir).newer).toEqual([]);
  });

  it('finds output written by a newer prism, and the highest version among it', () => {
    const a = stamp('packages/react/src/reactive/Button.ts', '99.0.0');
    stamp('packages/react/src/content/Card.ts', '99.2.0');
    stamp('packages/react/src/content/Chip.ts', VERSION);

    const scan = scanForNewerOutput(config(), tmpDir);

    expect(scan.newer.map((n) => n.version).sort()).toEqual(['99.0.0', '99.2.0']);
    expect(scan.newer.some((n) => n.path === a)).toBe(true);
    expect(scan.highest).toBe('99.2.0');
  });

  it('ignores a hand-written file sitting in an output directory', () => {
    mkdirSync(join(tmpDir, 'packages/react/src/reactive'), { recursive: true });
    writeFileSync(join(tmpDir, 'packages/react/src/reactive/README.md'), '# notes\n');
    expect(scanForNewerOutput(config(), tmpDir).scanned).toBe(0);
  });

  it('covers the whole-catalog outputs too', () => {
    stamp('types/react-jsx.d.ts', '99.0.0');
    const scan = scanForNewerOutput(config({ jsxTypes: { outDir: 'types' } }), tmpDir);
    expect(scan.newer).toHaveLength(1);
  });

  it('states what has and has not happened yet', () => {
    stamp('packages/react/src/reactive/Button.ts', '99.0.0');
    const scan = scanForNewerOutput(config(), tmpDir);
    // The tense is the point: this runs before any write, and the per-file
    // check that reports the same thing afterwards cannot say this.
    expect(describeDowngrade(scan, true)).toContain('Nothing has been written.');
    expect(describeDowngrade(scan, false)).not.toContain('Nothing has been written.');
    expect(describeDowngrade(scan, true)).toContain('99.0.0');
  });
});

describe('a generator overwriting newer output', () => {
  it('carries the version it replaced back to the caller', () => {
    const dir = join(tmpDir, 'out', 'reactive');
    mkdirSync(dir, { recursive: true });
    writeFileSync(
      join(dir, 'Button.ts'),
      '// Auto-generated by @arclux/prism 99.1.0 — do not edit manually\n// …a feature this version does not have…\n'
    );

    const result = generateReact(meta, config, tmpDir);

    expect(result.written).toBe(true);
    expect(result.priorVersion).toBe('99.1.0');
    // The revert really did happen — this is a report of damage done, not a
    // refusal, which is why the run that prints it is the last one that can.
    expect(readFileSync(result.path, 'utf-8')).toContain(HEADER);
  });

  it('stays quiet on the ordinary regenerate', () => {
    generateReact(meta, config, tmpDir);
    expect(generateReact(meta, config, tmpDir).priorVersion).toBe(null);
  });
});
