/**
 * Generates Angular standalone component (.ts) files from ComponentMeta.
 *
 * The component attaches to the custom element itself (element selector, no
 * inner element in the template). The v2 shape rendered a second `<arc-x>`
 * inside the template while the host — carrying the same tag — upgraded into
 * a real instance of the element too, so every wrapper double-rendered:
 * doubled borders and ARIA, with the bindings reaching only the inner copy.
 *
 * Host attachment also retires the entire attr-vs-property binding matrix the
 * v2 generator carried (boolean/array/object props, names that change under
 * lowercasing, template-grammar reserved words like `as`): inputs are accessor
 * pairs that write the DOM property on the host directly, which works
 * uniformly for every prop name and type.
 *
 * Events need no re-emit outputs — they fire natively from the host, so
 * `(arc-change)` binds as a plain DOM event. Only the `xChange` outputs that
 * desugar Angular's `[(x)]` two-way form are generated, fed by host listeners.
 */

import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { isPrismGenerated } from './header.js';
import { tsType, acceptsChildren } from './types.js';
import { deriveBindings, boundPropNames } from './bindings.js';

const HEADER = '// Auto-generated by @arclux/prism — do not edit manually';

/**
 * Convert a custom event name to a sync-method name that can't collide with
 * an @Input (props are never underscore-prefixed): 'arc-change' → '_onArcChange'.
 */
function syncMethodName(eventName) {
  const pascal = eventName.replace(/(?:^|-)([a-z])/g, (_, c) => c.toUpperCase());
  return `_on${pascal}`;
}

/**
 * Generate an Angular standalone component .ts file.
 * @param {import('./parser.js').ComponentMeta} meta
 * @param {object} config - angular config section
 * @param {string} root - project root
 * @returns {{ path: string, written: boolean }}
 */
export function generateAngular(meta, config, root) {
  const outDir = join(root, config.outDir, meta.tier);
  const outPath = join(outDir, `${meta.pascalName}.ts`);

  // Safety: never overwrite files without our header
  if (existsSync(outPath)) {
    const existing = readFileSync(outPath, 'utf-8');
    if (!isPrismGenerated(existing)) {
      return { path: outPath, written: false };
    }
  }

  mkdirSync(outDir, { recursive: true });

  const wcImport = config.wcPackage || `@${config.prefix}/${config.prefix}-ui`;
  // Per-component register subpath — registers only this element (guarded
  // define) and exports the element class, which types the host reference.
  const registerImport = `${wcImport}/${meta.tag.slice(config.prefix.length + 1)}`;
  const lines = [HEADER, ''];

  // Two-way bindings, derived from event detail keys that match prop names.
  // Angular's `[(x)]` desugars to `[x]` + `(xChange)`, so without the matching
  // output the banana-in-a-box form doesn't compile at all.
  const twoWay = deriveBindings(meta, config);
  const boundProps = boundPropNames(twoWay);
  const propTypes = new Map(meta.props.map((p) => [p.name, tsType(p)]));

  // Imports
  const angularImports = ['Component', 'ElementRef', 'inject'];
  if (meta.props.length > 0) angularImports.push('Input');
  if (boundProps.size > 0) angularImports.push('Output', 'EventEmitter');

  lines.push(`import { ${angularImports.join(', ')} } from '@angular/core';`);
  lines.push(`import { ${meta.className} } from '${registerImport}';`);
  lines.push('');

  // `<ng-content />` projects consumer children into the host's light DOM,
  // where the element's own shadow slots assign them — but only where a
  // default slot exists to receive them.
  const template = acceptsChildren(meta) ? '<ng-content />' : '';

  // Host listeners feed the `xChange` outputs. The element updates itself
  // before dispatching, so there is no local state to write back — the input
  // accessors below always read the live DOM property.
  const hostListeners = [...twoWay.keys()].map(
    (event) => `    '(${event})': '${syncMethodName(event)}($event)',`
  );

  // @Component decorator
  lines.push(`@Component({`);
  lines.push(`  selector: '${meta.tag}',`);
  lines.push(`  standalone: true,`);
  lines.push(`  template: \`${template}\`,`);
  if (hostListeners.length > 0) {
    lines.push(`  host: {`);
    lines.push(...hostListeners);
    lines.push(`  },`);
  }
  lines.push(`})`);
  lines.push(`export class ${meta.pascalName} {`);
  lines.push(`  private readonly _el: ${meta.className} = inject(ElementRef).nativeElement;`);

  // @Input() accessor pairs forwarding to the host element's properties. No
  // local defaults: an unbound input never fires the setter and the element
  // keeps its own default, so wrapper and element can't disagree.
  for (const prop of meta.props) {
    const type = propTypes.get(prop.name);
    lines.push('');
    lines.push(`  @Input() set ${prop.name}(value: ${type}) {`);
    lines.push(`    this._el.${prop.name} = value;`);
    lines.push(`  }`);
    lines.push(`  get ${prop.name}(): ${type} {`);
    lines.push(`    return this._el.${prop.name};`);
    lines.push(`  }`);
  }

  // `xChange` outputs — the second half of Angular's `[(x)]` two-way form.
  for (const prop of meta.props) {
    if (boundProps.has(prop.name)) {
      lines.push('');
      lines.push(`  @Output() ${prop.name}Change = new EventEmitter<${propTypes.get(prop.name)}>();`);
    }
  }

  for (const [event, props] of twoWay) {
    lines.push('');
    lines.push(`  ${syncMethodName(event)}(event: CustomEvent) {`);
    lines.push(`    const detail = event.detail as Record<string, unknown> | null;`);
    lines.push('    if (!detail) return;');
    for (const name of props) {
      lines.push(`    if ('${name}' in detail) {`);
      lines.push(`      this.${name}Change.emit(detail.${name} as ${propTypes.get(name)});`);
      lines.push('    }');
    }
    lines.push('  }');
  }

  lines.push('}');
  lines.push('');

  writeFileSync(outPath, lines.join('\n'));
  return { path: outPath, written: true };
}
