/**
 * Generates Angular standalone component (.ts) files from ComponentMeta.
 * Uses standalone components with CUSTOM_ELEMENTS_SCHEMA (Angular 17+ pattern).
 */

import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { isPrismGenerated } from './header.js';
import { tsType } from './types.js';
import { deriveBindings, boundPropNames, handlerName } from './bindings.js';

const HEADER = '// Auto-generated by @arclux/prism — do not edit manually';

/**
 * Format a default value for Angular @Input().
 */
function angularDefault(prop) {
  if (!prop.default) return undefined;
  const val = prop.default;
  if (val.startsWith("'") || val.startsWith('"')) return val;
  if (val === 'true' || val === 'false') return val;
  if (!isNaN(Number(val))) return val;
  if (val.startsWith('[') || val.startsWith('{')) return val;
  return `'${val}'`;
}

/**
 * Convert a custom event name to a camelCase handler name.
 * 'arc-change' → 'arcChange'
 */
function eventToCamel(eventName) {
  return eventName.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

/**
 * Generate an Angular standalone component .ts file.
 * @param {import('./parser.js').ComponentMeta} meta
 * @param {object} config - angular config section
 * @param {string} root - project root
 * @returns {{ path: string, written: boolean }}
 */
export function generateAngular(meta, config, root) {
  const outDir = join(root, config.outDir, meta.tier);
  const outPath = join(outDir, `${meta.pascalName}.ts`);

  // Safety: never overwrite files without our header
  if (existsSync(outPath)) {
    const existing = readFileSync(outPath, 'utf-8');
    if (!isPrismGenerated(existing)) {
      return { path: outPath, written: false };
    }
  }

  mkdirSync(outDir, { recursive: true });

  const wcImport = config.wcPackage || `@${config.prefix}/${config.prefix}-ui`;
  // Per-component register subpath — registers only this element (guarded define)
  const registerImport = `${wcImport}/${meta.tag.slice(config.prefix.length + 1)}`;
  const lines = [HEADER, ''];

  // Two-way bindings, derived from event detail keys that match prop names.
  // Angular's `[(x)]` desugars to `[x]` + `(xChange)`, so without the matching
  // output the banana-in-a-box form doesn't compile at all.
  const twoWay = deriveBindings(meta, config);
  const boundProps = boundPropNames(twoWay);
  const propTypes = new Map(meta.props.map((p) => [p.name, tsType(p)]));

  // Handler names are shared between the template and the class body below.
  // Seeded with prop and output names so a handler can't shadow either.
  const handlers = new Map();
  {
    const used = new Set([
      ...meta.props.map((p) => p.name),
      ...meta.props.filter((p) => boundProps.has(p.name)).map((p) => `${p.name}Change`),
      ...meta.events.map(eventToCamel),
    ]);
    for (const event of twoWay.keys()) handlers.set(event, handlerName(event, used));
  }

  // Imports
  const angularImports = ['Component', 'CUSTOM_ELEMENTS_SCHEMA'];
  if (meta.props.length > 0) angularImports.push('Input');
  if (meta.events.length > 0) angularImports.push('Output', 'EventEmitter');

  lines.push(`import { ${angularImports.join(', ')} } from '@angular/core';`);
  lines.push(`import '${registerImport}';`);
  lines.push('');

  // Build template. Boolean/Array/Object bind as DOM properties: `[attr.x]`
  // stringifies via toString() (`[1,2,3]` → "1,2,3", objects → "[object
  // Object]"), which Lit's JSON.parse attribute converter then rejects and
  // nulls. String/Number reflect fine as attributes.
  //
  // Every expression is qualified with `this.` — Angular's template grammar has
  // its own keyword list (`as`, `in`, `let`, `var`, `this`, …) that doesn't
  // match JavaScript's, and a bare member of it doesn't parse. `arc-text`
  // declares `as`, so `[attr.as]="as"` failed to compile. The class field is
  // unaffected: reserved words are legal property names. `this.as` is legal for
  // every name, so this retires the whole class of problem rather than
  // special-casing the words that happen to collide today.
  const templateAttrs = meta.props.map((p) => {
    if (p.type === 'Boolean' || p.type === 'Array' || p.type === 'Object') {
      return `[${p.name}]="this.${p.name}"`;
    }
    return `[attr.${p.name}]="this.${p.name}"`;
  });

  // Add event listeners in template. Events that write a prop back route
  // through a class method instead, so the write and both emits stay together.
  for (const event of meta.events) {
    if (handlers.has(event)) {
      templateAttrs.push(`(${event})="this.${handlers.get(event)}($event)"`);
    } else {
      templateAttrs.push(`(${event})="this.${eventToCamel(event)}.emit($event)"`);
    }
  }

  let template;
  if (templateAttrs.length > 0) {
    template = `<${meta.tag} ${templateAttrs.join(' ')}><ng-content /></${meta.tag}>`;
  } else {
    template = `<${meta.tag}><ng-content /></${meta.tag}>`;
  }

  // @Component decorator
  lines.push(`@Component({`);
  lines.push(`  selector: '${meta.tag}',`);
  lines.push(`  standalone: true,`);
  lines.push(`  schemas: [CUSTOM_ELEMENTS_SCHEMA],`);
  lines.push(`  template: \`${template}\`,`);
  lines.push(`})`);
  lines.push(`export class ${meta.pascalName} {`);

  // @Input() properties
  for (const prop of meta.props) {
    const def = angularDefault(prop);
    if (def !== undefined) {
      lines.push(`  @Input() ${prop.name}: ${tsType(prop)} = ${def};`);
    } else {
      lines.push(`  @Input() ${prop.name}?: ${tsType(prop)};`);
    }
  }

  // @Output() events
  for (const event of meta.events) {
    const camel = eventToCamel(event);
    lines.push(`  @Output() ${camel} = new EventEmitter<CustomEvent>();`);
  }

  // `xChange` outputs — the second half of Angular's `[(x)]` two-way form.
  for (const prop of meta.props) {
    if (boundProps.has(prop.name)) {
      lines.push(`  @Output() ${prop.name}Change = new EventEmitter<${tsType(prop)}>();`);
    }
  }

  // Write-back handlers. The local @Input is updated as well as emitted, so a
  // one-way `[value]` consumer still sees the element's current state rather
  // than having the stale bound value pushed back on the next change detection.
  for (const [event, fn] of handlers) {
    lines.push('');
    lines.push(`  ${fn}(event: CustomEvent) {`);
    lines.push(`    this.${eventToCamel(event)}.emit(event);`);
    lines.push(`    const detail = event.detail as Record<string, unknown> | null;`);
    lines.push('    if (!detail) return;');
    for (const name of twoWay.get(event)) {
      lines.push(`    if ('${name}' in detail) {`);
      lines.push(`      const next = detail.${name} as ${propTypes.get(name)};`);
      lines.push(`      this.${name} = next;`);
      lines.push(`      this.${name}Change.emit(next);`);
      lines.push('    }');
    }
    lines.push('  }');
  }

  lines.push('}');
  lines.push('');

  writeFileSync(outPath, lines.join('\n'));
  return { path: outPath, written: true };
}
