/**
 * Updates barrel (index) files for web components and framework wrappers.
 * Append-only — never removes existing exports.
 *
 * Data-driven: each framework defines its export patterns via a config object,
 * and two generic functions handle tier and root barrel updates.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';

const BARREL_HEADER = '// Auto-generated by @arclux/prism — do not edit manually';

/**
 * Test whether an export for `needle` already exists in barrel `content`.
 * Uses identifier boundaries rather than a plain substring so that a component
 * whose name is a substring of an already-exported one (e.g. `Button` inside
 * `IconButton`) is not mistaken for a duplicate and silently dropped.
 */
function alreadyExported(content, needle) {
  const escaped = needle.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`(?<![\\w$])${escaped}(?![\\w$])`).test(content);
}

// ── Framework barrel configs ────────────────────────────────

/**
 * @typedef {Object} BarrelConfig
 * @property {string} barrelExt - barrel file extension (e.g. '.js', '.ts')
 * @property {(meta: import('./parser.js').ComponentMeta) => string} existsCheck
 *   - string to search for in existing content to detect duplicates
 * @property {(meta: import('./parser.js').ComponentMeta) => string} tierExportLines
 *   - the export line(s) to append to a tier barrel
 * @property {(meta: import('./parser.js').ComponentMeta) => string} rootExportLines
 *   - the export line(s) to append to a root barrel
 * @property {string} separator - string between existing content and new lines
 * @property {'root-merge'|'root-append'} [rootStrategy] - WC uses merge into existing tier line
 */

/** Web Components barrel config — special root strategy that merges into existing tier export. */
const wcConfig = {
  barrelExt: '.js',
  existsCheck: (meta) => meta.className,
  tierExportLines: (meta, prefix = 'arc') => {
    const fileName = meta.tag.replace(new RegExp('^' + prefix + '-'), '');
    return `export { ${meta.className} } from './${fileName}.js';`;
  },
  separator: '\n',
  rootStrategy: 'root-merge',
  rootExportLines: (meta) => `export { ${meta.className} } from './${meta.tier}/index.js';`,
};

/** Shared config factory for frameworks that use `export { X } from './X.js'` + type exports. */
function typedJsConfig() {
  return {
    barrelExt: '.ts',
    existsCheck: (meta) => meta.pascalName,
    rootExistsCheck: (meta) => `{ ${meta.pascalName} }`,
    tierExportLines: (meta) => [
      `export { ${meta.pascalName} } from './${meta.pascalName}.js';`,
      `export type { ${meta.pascalName}Props } from './${meta.pascalName}.js';`,
    ].join('\n'),
    separator: '\n\n',
    rootStrategy: 'root-append',
    rootExportLines: (meta) => [
      `export { ${meta.pascalName} } from './${meta.tier}/${meta.pascalName}.js';`,
      `export type { ${meta.pascalName}Props } from './${meta.tier}/${meta.pascalName}.js';`,
    ].join('\n'),
  };
}

/** Shared config factory for SFC frameworks (Vue/Svelte) using `export { default as X }`. */
function sfcConfig(ext) {
  return {
    barrelExt: '.ts',
    existsCheck: (meta) => meta.pascalName,
    rootExistsCheck: (meta) => `{ default as ${meta.pascalName} }`,
    tierExportLines: (meta) =>
      `export { default as ${meta.pascalName} } from './${meta.pascalName}.${ext}';`,
    separator: '\n',
    rootStrategy: 'root-append',
    rootExportLines: (meta) =>
      `export { default as ${meta.pascalName} } from './${meta.tier}/${meta.pascalName}.${ext}';`,
  };
}

/**
 * Plain named-export config (Angular) — no type exports, no default-as.
 * Extensionless specifiers on purpose: ngc emits .mjs whose imports keep the
 * source specifier verbatim, so a '.js' suffix breaks ng-packagr's flatten
 * step ("Could not resolve ./X.js from dist/esm2022/index.mjs").
 */
const angularConfig = {
  barrelExt: '.ts',
  existsCheck: (meta) => meta.pascalName,
  rootExistsCheck: (meta) => `{ ${meta.pascalName} }`,
  tierExportLines: (meta) =>
    `export { ${meta.pascalName} } from './${meta.pascalName}';`,
  separator: '\n',
  rootStrategy: 'root-append',
  rootExportLines: (meta) =>
    `export { ${meta.pascalName} } from './${meta.tier}/${meta.pascalName}';`,
};

const FRAMEWORK_CONFIGS = {
  wc: wcConfig,
  react: typedJsConfig(),
  solid: typedJsConfig(),
  preact: typedJsConfig(),
  vue: sfcConfig('vue'),
  svelte: sfcConfig('svelte'),
  angular: angularConfig,
};

// ── Generic barrel update functions ─────────────────────────

/**
 * Update a tier-level barrel file (e.g. `content/index.js`).
 * @param {BarrelConfig} cfg
 * @param {import('./parser.js').ComponentMeta} meta
 * @param {string} outDir - absolute path to framework src dir
 * @returns {{ path: string, updated: boolean }}
 */
function updateTierBarrel(cfg, meta, outDir, prefix = 'arc') {
  const barrelPath = join(outDir, meta.tier, `index${cfg.barrelExt}`);
  // Create the barrel when a tier is new — silently skipping here left whole
  // tiers (data, typography) without barrels and thus unreachable via exports.
  if (!existsSync(barrelPath)) {
    mkdirSync(dirname(barrelPath), { recursive: true });
    writeFileSync(barrelPath, BARREL_HEADER + '\n');
  }

  const content = readFileSync(barrelPath, 'utf-8');
  const needle = cfg.existsCheck(meta);

  if (alreadyExported(content, needle)) {
    return { path: barrelPath, updated: false };
  }

  const exportLines = cfg.tierExportLines(meta, prefix);
  const updated = content.trimEnd() + cfg.separator + exportLines + '\n';
  writeFileSync(barrelPath, updated);
  return { path: barrelPath, updated: true };
}

/**
 * Update a root-level barrel file (e.g. `index.ts`).
 * Supports two strategies:
 *   - 'root-merge': merge new export name into an existing tier re-export line (WC style)
 *   - 'root-append': append new export line(s) at end of file (all frameworks)
 * @param {BarrelConfig} cfg
 * @param {import('./parser.js').ComponentMeta} meta
 * @param {string} outDir - absolute path to framework src dir
 * @returns {{ path: string, updated: boolean }}
 */
function updateRootBarrel(cfg, meta, outDir) {
  const barrelPath = join(outDir, `index${cfg.barrelExt}`);
  if (!existsSync(barrelPath)) {
    mkdirSync(dirname(barrelPath), { recursive: true });
    writeFileSync(barrelPath, BARREL_HEADER + '\n');
  }

  const content = readFileSync(barrelPath, 'utf-8');
  const needle = cfg.rootExistsCheck
    ? cfg.rootExistsCheck(meta)
    : cfg.existsCheck(meta);

  if (alreadyExported(content, needle)) {
    return { path: barrelPath, updated: false };
  }

  if (cfg.rootStrategy === 'root-merge') {
    // WC-style: try to add to an existing tier re-export line
    const tierExportPattern = new RegExp(
      `^(export\\s*\\{[^}]*\\}\\s*from\\s*['"]\\./${meta.tier}/index\\.js['"];?)$`,
      'm'
    );
    const tierMatch = content.match(tierExportPattern);

    if (tierMatch) {
      const oldLine = tierMatch[0];
      const newLine = oldLine.replace(
        /\}\s*from/,
        `, ${meta.className} } from`
      );
      writeFileSync(barrelPath, content.replace(oldLine, newLine));
    } else {
      const exportLine = cfg.rootExportLines(meta);
      const updated = content.trimEnd() + '\n' + exportLine + '\n';
      writeFileSync(barrelPath, updated);
    }
  } else {
    // Append strategy — all other frameworks
    const exportLines = cfg.rootExportLines(meta);
    const updated = content.trimEnd() + cfg.separator + exportLines + '\n';
    writeFileSync(barrelPath, updated);
  }

  return { path: barrelPath, updated: true };
}

// ── Public API ──────────────────────────────────────────────

export function updateWCBarrel(meta, componentsDir, prefix = 'arc') {
  return updateTierBarrel(FRAMEWORK_CONFIGS.wc, meta, componentsDir, prefix);
}

export function updateWCRootBarrel(meta, componentsDir) {
  return updateRootBarrel(FRAMEWORK_CONFIGS.wc, meta, componentsDir);
}

export function updateReactTierBarrel(meta, reactDir) {
  return updateTierBarrel(FRAMEWORK_CONFIGS.react, meta, reactDir);
}

export function updateReactRootBarrel(meta, reactDir) {
  return updateRootBarrel(FRAMEWORK_CONFIGS.react, meta, reactDir);
}

export function updateVueTierBarrel(meta, vueDir) {
  return updateTierBarrel(FRAMEWORK_CONFIGS.vue, meta, vueDir);
}

export function updateVueRootBarrel(meta, vueDir) {
  return updateRootBarrel(FRAMEWORK_CONFIGS.vue, meta, vueDir);
}

export function updateSvelteTierBarrel(meta, svelteDir) {
  return updateTierBarrel(FRAMEWORK_CONFIGS.svelte, meta, svelteDir);
}

export function updateSvelteRootBarrel(meta, svelteDir) {
  return updateRootBarrel(FRAMEWORK_CONFIGS.svelte, meta, svelteDir);
}

export function updateAngularTierBarrel(meta, angularDir) {
  return updateTierBarrel(FRAMEWORK_CONFIGS.angular, meta, angularDir);
}

export function updateAngularRootBarrel(meta, angularDir) {
  return updateRootBarrel(FRAMEWORK_CONFIGS.angular, meta, angularDir);
}

export function updateSolidTierBarrel(meta, solidDir) {
  return updateTierBarrel(FRAMEWORK_CONFIGS.solid, meta, solidDir);
}

export function updateSolidRootBarrel(meta, solidDir) {
  return updateRootBarrel(FRAMEWORK_CONFIGS.solid, meta, solidDir);
}

export function updatePreactTierBarrel(meta, preactDir) {
  return updateTierBarrel(FRAMEWORK_CONFIGS.preact, meta, preactDir);
}

export function updatePreactRootBarrel(meta, preactDir) {
  return updateRootBarrel(FRAMEWORK_CONFIGS.preact, meta, preactDir);
}

// ── Barrel reconciliation ───────────────────────────────────

/** Extensions a specifier may actually be on disk as. */
const SOURCE_EXTS = ['.ts', '.tsx', '.js', '.mjs', '.vue', '.svelte'];

/**
 * Resolve a relative specifier to a file on disk, or null.
 *
 * A barrel's specifier rarely matches its file verbatim: TypeScript writes
 * `./Toast.js` for `Toast.ts`, Angular omits the extension entirely, and a
 * consumer may point at a directory and mean its index. All of those must be
 * treated as resolving, or the prune below deletes working exports.
 */
function resolveSpecifier(dir, specifier) {
  const base = join(dir, specifier);
  const candidates = [base];

  const withoutJs = base.replace(/\.js$/, '');
  if (withoutJs !== base) candidates.push(...SOURCE_EXTS.map((e) => withoutJs + e));
  if (!/\.[a-z]+$/.test(base)) candidates.push(...SOURCE_EXTS.map((e) => base + e));
  // A directory specifier means that directory's barrel.
  candidates.push(...SOURCE_EXTS.map((e) => join(base, `index${e}`)));

  return candidates.find((c) => existsSync(c) && statSync(c).isFile()) ?? null;
}

/** Whether a resolved path is itself a barrel. */
function targetIsBarrel(path) {
  return /(^|[\\/])index\.[a-z]+$/.test(path);
}

/** `default as Foo` / `Foo as Bar` → the name the importer sees. */
function sourceName(identifier) {
  return identifier.split(/\s+as\s+/)[0].trim();
}

/**
 * Repair barrels that export things which no longer exist.
 *
 * The per-component updates above are append-only, which is the right shape for
 * watch and single-file mode: they see one meta and must not judge the rest of
 * the barrel on that basis. The cost is that a deleted component's export lines
 * survive forever, and the specifier points at a file the generators have stopped
 * writing — so the barrel stops compiling:
 *
 *   error TS2307: Cannot find module './ToastManager.js'
 *
 * That breaks the build of whoever imports the barrel rather than prism's own, and
 * only when someone typechecks the wrapper package. So unlike `sweepOrphans` this
 * is not gated behind --prune: an unbuildable barrel is a bug, not untidiness.
 *
 * Decided by *resolution*, never by naming convention. An earlier attempt rebuilt
 * the expected specifier set from the metas and deleted anything absent from it,
 * which quietly stripped 136 working exports from a project whose web-component
 * barrels point at `./accordion.register.js` rather than the `./accordion.js` this
 * file would have written — a barrel prism does not generate at all. Asking the
 * filesystem cannot be wrong about that.
 *
 * @param {object} config - normalized config
 * @param {string} root - project root
 * @returns {{ path: string, removed: string[] }[]} one entry per barrel changed
 */
export function pruneBarrels(config, root) {
  const dirs = [];
  if (config.components) dirs.push(join(root, config.components));
  for (const key of ['react', 'vue', 'svelte', 'angular', 'solid', 'preact']) {
    if (config[key]?.barrels) dirs.push(join(root, config[key].outDir));
  }

  const changed = [];
  for (const dir of dirs) {
    // Tier barrels before root barrels: a root barrel re-exports tier barrels by
    // identifier, so it has to see them already repaired.
    for (const tier of config.tiers) {
      record(changed, pruneBarrelFile(join(dir, tier)));
    }
    record(changed, pruneBarrelFile(dir));
  }
  return changed;
}

function record(changed, results) {
  for (const r of results) if (r.removed.length > 0) changed.push(r);
}

/** Repair every barrel file directly inside `dir`. */
function pruneBarrelFile(dir) {
  if (!existsSync(dir)) return [];
  const out = [];
  for (const ext of SOURCE_EXTS) {
    const path = join(dir, `index${ext}`);
    if (!existsSync(path)) continue;
    const result = repairBarrel(path, dir);
    if (result) out.push(result);
  }
  return out;
}

function repairBarrel(path, dir) {
  const content = readFileSync(path, 'utf-8');
  const removed = [];
  const lines = [];

  for (const line of content.split('\n')) {
    const match = line.match(/^export\s+(?:type\s+)?\{([^}]*)\}\s*from\s*['"](\.[^'"]*)['"];?\s*$/);
    if (!match) { lines.push(line); continue; }

    const [, identifiers, specifier] = match;
    const resolved = resolveSpecifier(dir, specifier);

    // Unresolvable specifier: the whole line is broken.
    if (!resolved) {
      removed.push(specifier);
      continue;
    }

    // Re-export of another barrel: the path is fine, so check that the names are
    // still there. Nothing else can catch a name that a tier barrel stopped
    // exporting — the file itself exists either way.
    if (targetIsBarrel(resolved)) {
      const targetText = readFileSync(resolved, 'utf-8');
      const names = identifiers.split(',').map((x) => x.trim()).filter(Boolean);
      const live = names.filter((n) => hasIdentifier(targetText, sourceName(n)));
      if (live.length === names.length) { lines.push(line); continue; }
      for (const n of names) {
        if (!hasIdentifier(targetText, sourceName(n))) removed.push(sourceName(n));
      }
      if (live.length > 0) lines.push(line.replace(/\{[^}]*\}/, `{ ${live.join(', ')} }`));
      continue;
    }

    lines.push(line);
  }

  if (removed.length === 0) return null;
  // trimEnd + single newline, matching how the append path above writes, so a
  // prune never shows up in a diff as a whitespace change.
  writeFileSync(path, lines.join('\n').trimEnd() + '\n');
  return { path, removed: [...new Set(removed)] };
}

/** Identifier-boundary search, so `Button` does not match inside `IconButton`. */
function hasIdentifier(text, name) {
  const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`(?<![\\w$])${escaped}(?![\\w$])`).test(text);
}
