/**
 * Recognizes prism's own "do not edit" sentinel in an existing file so the
 * generators know they may overwrite it.
 *
 * The match is deliberately independent of the package/org name: the scope was
 * renamed (`@arclight` → `@arclux`), and checking for the exact current header
 * would treat every file written under the old name as hand-edited and refuse
 * to regenerate it forever. Matching the stable part of the sentinel lets a
 * renamed tool still recognize — and refresh — its own past output.
 */
const GENERATED_SENTINEL = /Auto-generated by @[\w.-]+\/prism — do not edit manually/;

/**
 * @param {string} content - existing file contents
 * @returns {boolean} true if the file was generated by prism (any org name)
 */
export function isPrismGenerated(content) {
  // Only inspect the head of the file: the sentinel always lives in the opening
  // comment, and this avoids matching the phrase if it appears in user content.
  return GENERATED_SENTINEL.test(content.slice(0, 300));
}
