import { existsSync, readFileSync, unlinkSync } from 'node:fs';
import { createRequire } from 'node:module';

/** The running generator's version, read from prism's own package.json. */
export const VERSION = createRequire(import.meta.url)('../../package.json').version;

/**
 * The sentinel every generated file opens with, in each comment syntax the
 * outputs use.
 *
 * The version is part of it, and that is the whole point. `prism` rewrites
 * every wrapper it owns from whatever version is installed, so running an older
 * one does not error — it *reverts*. Regenerating a 235-file catalog on 2.12.0
 * silently undid 205 Angular, 10 React, 10 Preact and 10 Solid files, and the
 * only signal was a large diff in generated files nobody reads, which CI
 * reported as "generated files are out of date" — wording that reads as *stale
 * committed output* and invites the exact wrong fix: commit the revert.
 *
 * With the version in the first line of every file, a downgrade announces
 * itself in the diff rather than hiding in it, and `generatedVersion` below
 * lets prism say so out loud before it overwrites anything.
 */
export const HEADER = `// Auto-generated by @arclux/prism ${VERSION} — do not edit manually`;
export const HEADER_HTML = `<!-- Auto-generated by @arclux/prism ${VERSION} — do not edit manually -->`;
export const HEADER_CSS = `/* Auto-generated by @arclux/prism ${VERSION} — do not edit manually */`;

/**
 * Recognizes prism's own "do not edit" sentinel in an existing file so the
 * generators know they may overwrite it.
 *
 * The match is deliberately independent of the package/org name: the scope was
 * renamed (`@arclight` → `@arclux`), and checking for the exact current header
 * would treat every file written under the old name as hand-edited and refuse
 * to regenerate it forever. Matching the stable part of the sentinel lets a
 * renamed tool still recognize — and refresh — its own past output.
 *
 * The version is optional for exactly the same reason, and this is the half of
 * the change that had to be got right: every file written before 2.14.0 carries
 * no version, and a sentinel that insisted on one would have classified all of
 * them as hand-edited — turning a feature meant to *expose* a mass revert into
 * a release that silently stopped regenerating anything at all.
 */
const GENERATED_SENTINEL =
  /Auto-generated by @[\w.-]+\/prism(?:\s+([\w.+-]+))? — do not edit manually/;

/**
 * @param {string} content - existing file contents
 * @returns {boolean} true if the file was generated by prism (any org name)
 */
export function isPrismGenerated(content) {
  // Only inspect the head of the file: the sentinel always lives in the opening
  // comment, and this avoids matching the phrase if it appears in user content.
  return GENERATED_SENTINEL.test(content.slice(0, 300));
}

/**
 * The version stamped into an already-generated file, or null when it carries
 * none — either because prism didn't write it, or because it was written before
 * 2.14.0 started stamping.
 *
 * @param {string} content - existing file contents
 * @returns {string|null}
 */
export function generatedVersion(content) {
  return GENERATED_SENTINEL.exec(content.slice(0, 300))?.[1] ?? null;
}

/**
 * Compare two dotted versions. Positive when `a` is newer.
 *
 * Deliberately small: this exists to answer one question — is the file on disk
 * from a newer prism than the one about to overwrite it — and pulling a semver
 * dependency into a zero-dependency generator to answer it would cost more than
 * it settles. A prerelease sorts below its release, which is the only ordering
 * subtlety that comes up in practice (3.0.0-rc.1 before 3.0.0).
 *
 * @param {string} a
 * @param {string} b
 * @returns {number}
 */
export function compareVersions(a, b) {
  const parts = (v) => v.split('-')[0].split('.').map((n) => Number.parseInt(n, 10) || 0);
  const [x, y] = [parts(a), parts(b)];
  for (let i = 0; i < Math.max(x.length, y.length); i++) {
    const d = (x[i] ?? 0) - (y[i] ?? 0);
    if (d !== 0) return d;
  }
  return (a.includes('-') ? 0 : 1) - (b.includes('-') ? 0 : 1);
}

/**
 * What a generator should report about the file it is about to replace.
 *
 * Called from the one place that has already read the existing file for the
 * overwrite check, so it costs no extra I/O. Returns the stamped version only
 * when it is *newer* than the running generator — the downgrade case — because
 * that is the only one worth carrying back to the CLI. Same or older is the
 * normal path and says nothing.
 *
 * @param {string} content - existing file contents
 * @returns {string|null}
 */
export function newerVersionIn(content) {
  const prior = generatedVersion(content);
  return prior && compareVersions(prior, VERSION) > 0 ? prior : null;
}

/**
 * Decide whether a generator may write to `outPath`, and what was there before.
 *
 * Every wrapper generator opened with the same six lines — stat, read, check the
 * sentinel, bail if it isn't ours — and each one now also has to report the
 * version it is about to overwrite. Six copies of that is six places for the
 * downgrade check to be quietly omitted from, which is the failure mode the
 * check exists to catch.
 *
 * @param {string} outPath
 * @returns {{ ours: boolean, priorVersion: string|null }} `ours` is false for a
 *   hand-written file at a generated path; `priorVersion` is set only when the
 *   file was written by a *newer* prism than this one.
 */
export function claimOutput(outPath) {
  if (!existsSync(outPath)) return { ours: true, priorVersion: null };
  const existing = readFileSync(outPath, 'utf-8');
  if (!isPrismGenerated(existing)) return { ours: false, priorVersion: null };
  return { ours: true, priorVersion: newerVersionIn(existing) };
}

/**
 * Delete output prism no longer produces for a component.
 *
 * A component that gains a `@click` handler (or any other interactivity signal)
 * flips from `static` to `interactive`, and the CSS/HTML generators start
 * skipping it. Skipping only means "don't write" — so whatever an earlier run
 * left on disk stays there forever, never overwritten because the generator
 * bails before the write and never refreshed because nothing else owns the
 * path. Consumers keep loading a file that no current build produces, and it
 * silently drifts from the component it claims to describe.
 *
 * Removal is gated on the sentinel, exactly like the overwrite path: a
 * hand-written file sitting at a generated path is never deleted.
 *
 * `apply: false` reports what is stale without touching disk — the default,
 * because deleting output prism can no longer regenerate is irreversible
 * outside version control.
 *
 * @param {string} outPath
 * @param {{ apply?: boolean }} [opts]
 * @returns {{ path: string, stale: boolean, removed: boolean }}
 */
export function removeGenerated(outPath, { apply = false } = {}) {
  const miss = { path: outPath, stale: false, removed: false };
  if (!existsSync(outPath)) return miss;
  if (!isPrismGenerated(readFileSync(outPath, 'utf-8'))) return miss;
  if (apply) unlinkSync(outPath);
  return { path: outPath, stale: true, removed: apply };
}
