/**
 * Generates Preact component (.tsx) files from ComponentMeta.
 * Native CE support — no wrapper library needed.
 */

import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { isPrismGenerated } from './header.js';

const HEADER = '// Auto-generated by @arclux/prism — do not edit manually';

/**
 * Convert a custom event name to a handler prop name.
 * 'arc-change' → 'onArcChange'
 */
function eventToHandlerName(eventName) {
  return 'on' + eventName
    .split('-')
    .map((s) => s[0].toUpperCase() + s.slice(1))
    .join('');
}

/**
 * Map a WC property type to a TypeScript type string.
 */
function tsType(prop) {
  if (prop.values && prop.values.length > 0) {
    return prop.values.map((v) => `'${v}'`).join(' | ');
  }
  switch (prop.type) {
    case 'Boolean': return 'boolean';
    case 'Number':  return 'number';
    case 'Array':   return 'unknown[]';
    case 'Object':  return 'Record<string, unknown>';
    default:        return 'string';
  }
}

/**
 * Generate a Preact component .tsx file.
 * @param {import('./parser.js').ComponentMeta} meta
 * @param {object} config - preact config section
 * @param {string} root - project root
 * @returns {{ path: string, written: boolean }}
 */
export function generatePreact(meta, config, root) {
  const outDir = join(root, config.outDir, meta.tier);
  const outPath = join(outDir, `${meta.pascalName}.tsx`);

  // Safety: never overwrite files without our header
  if (existsSync(outPath)) {
    const existing = readFileSync(outPath, 'utf-8');
    if (!isPrismGenerated(existing)) {
      return { path: outPath, written: false };
    }
  }

  mkdirSync(outDir, { recursive: true });

  const wcImport = config.wcPackage || `@${config.prefix}/${config.prefix}-ui`;
  // Per-component register subpath — registers only this element (guarded define)
  const registerImport = `${wcImport}/${meta.tag.slice(config.prefix.length + 1)}`;
  const lines = [HEADER, ''];

  const hasEvents = meta.events.length > 0;

  lines.push(`import { type FunctionComponent } from 'preact';`);
  // Preact lowercases `on*` handler names, so hyphenated custom events like
  // `arc-click` can't be bound as JSX props — attach them via addEventListener
  // in a layout effect against a ref instead.
  if (hasEvents) {
    lines.push(`import { useLayoutEffect, useRef } from 'preact/hooks';`);
  }
  lines.push(`import '${registerImport}';`);
  lines.push('');

  // Props interface
  lines.push(`export interface ${meta.pascalName}Props {`);
  for (const prop of meta.props) {
    lines.push(`  ${prop.name}?: ${tsType(prop)};`);
  }
  for (const event of meta.events) {
    lines.push(`  ${eventToHandlerName(event)}?: (e: CustomEvent) => void;`);
  }
  lines.push('  children?: preact.ComponentChildren;');
  lines.push('  [key: string]: unknown;');
  lines.push('}');
  lines.push('');

  // Component
  const destructured = meta.props.map((p) => p.name);
  for (const event of meta.events) destructured.push(eventToHandlerName(event));
  destructured.push('children');
  const destructStr = destructured.join(', ');

  const attrs = meta.props.map((p) => `${p.name}={${p.name}}`).join(' ');
  const attrStr = attrs ? ` ${attrs} {...rest}` : ' {...rest}';

  if (hasEvents) {
    lines.push(`export const ${meta.pascalName}: FunctionComponent<${meta.pascalName}Props> = ({ ${destructStr}, ...rest }) => {`);
    lines.push(`  const ref = useRef<HTMLElement>(null);`);
    lines.push(`  useLayoutEffect(() => {`);
    lines.push(`    const el = ref.current;`);
    lines.push(`    if (!el) return;`);
    lines.push(`    const listeners: Array<[string, EventListener]> = [];`);
    for (const event of meta.events) {
      const handler = eventToHandlerName(event);
      lines.push(`    if (${handler}) {`);
      lines.push(`      const fn: EventListener = (e) => ${handler}(e as CustomEvent);`);
      lines.push(`      el.addEventListener('${event}', fn);`);
      lines.push(`      listeners.push(['${event}', fn]);`);
      lines.push(`    }`);
    }
    lines.push(`    return () => listeners.forEach(([name, fn]) => el.removeEventListener(name, fn));`);
    lines.push(`  }, [${meta.events.map(eventToHandlerName).join(', ')}]);`);
    lines.push(`  return (`);
    lines.push(`    <${meta.tag} ref={ref}${attrStr}>`);
    lines.push(`      {children}`);
    lines.push(`    </${meta.tag}>`);
    lines.push(`  );`);
    lines.push(`};`);
  } else {
    lines.push(`export const ${meta.pascalName}: FunctionComponent<${meta.pascalName}Props> = ({ ${destructStr}, ...rest }) => (`);
    lines.push(`  <${meta.tag}${attrStr}>`);
    lines.push(`    {children}`);
    lines.push(`  </${meta.tag}>`);
    lines.push(`);`);
  }
  lines.push('');

  writeFileSync(outPath, lines.join('\n'));
  return { path: outPath, written: true };
}
