/**
 * Generates Svelte 5 component (.svelte) files from ComponentMeta.
 * Uses $props() runes and Snippet type for children.
 */

import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { isPrismGenerated } from './header.js';
import { tsType } from './types.js';
import { deriveBindings, boundPropNames, handlerName } from './bindings.js';
import { localNames } from './identifiers.js';

const HEADER = '<!-- Auto-generated by @arclux/prism — do not edit manually -->';

/**
 * Format a default value for Svelte destructuring.
 */
function svelteDefault(prop) {
  if (!prop.default) return undefined;
  const val = prop.default;
  if (val.startsWith("'") || val.startsWith('"')) return val;
  if (val === 'true' || val === 'false') return val;
  if (!isNaN(Number(val))) return val;
  return val;
}

/**
 * Generate a Svelte 5 .svelte file for a component.
 * @param {import('./parser.js').ComponentMeta} meta
 * @param {object} config - svelte config section
 * @param {string} root - project root
 * @returns {{ path: string, written: boolean }}
 */
export function generateSvelte(meta, config, root) {
  const outDir = join(root, config.outDir, meta.tier);
  const outPath = join(outDir, `${meta.pascalName}.svelte`);

  // Safety: never overwrite files without our header
  if (existsSync(outPath)) {
    const existing = readFileSync(outPath, 'utf-8');
    if (!isPrismGenerated(existing)) {
      return { path: outPath, written: false };
    }
  }

  mkdirSync(outDir, { recursive: true });

  const wcImport = config.wcPackage || `@${config.prefix}/${config.prefix}-ui`;
  // Per-component register subpath — registers only this element (guarded define)
  const registerImport = `${wcImport}/${meta.tag.slice(config.prefix.length + 1)}`;
  const lines = [HEADER];

  // <script lang="ts">
  lines.push('<script lang="ts">');
  lines.push(`  import '${registerImport}';`);
  lines.push(`  import type { Snippet } from 'svelte';`);
  lines.push('');

  // Props interface
  lines.push('  interface Props {');
  for (const prop of meta.props) {
    lines.push(`    ${prop.name}?: ${tsType(prop)};`);
  }
  lines.push('    children?: Snippet;');
  lines.push('    [key: string]: unknown;');
  lines.push('  }');
  lines.push('');

  // Two-way bindings, derived from event detail keys that match prop names.
  const bindings = deriveBindings(meta, config);
  const boundProps = boundPropNames(bindings);
  const propTypes = new Map(meta.props.map((p) => [p.name, tsType(p)]));

  // A prop named after a reserved word can't be a binding name, so it is
  // renamed on the way in (`for: forProp`). The interface key, the attribute
  // and the element's own property all keep the real name.
  const locals = localNames(meta.props);
  const renamed = (name) => locals.get(name) !== name;

  // $props() destructuring with defaults. Bound props are wrapped in
  // $bindable() so the wrapper can write to them; this is backwards
  // compatible — a parent passing a plain value keeps working, the write
  // just stays local.
  const destructured = [];
  for (const prop of meta.props) {
    const def = svelteDefault(prop);
    const init = boundProps.has(prop.name) ? `$bindable(${def ?? ''})` : def;
    const binding = renamed(prop.name)
      ? `${prop.name}: ${locals.get(prop.name)}`
      : prop.name;
    if (init !== undefined) {
      destructured.push(`${binding} = ${init}`);
    } else {
      destructured.push(binding);
    }
  }
  destructured.push('children');
  destructured.push('...rest');

  lines.push(`  let { ${destructured.join(', ')} }: Props = $props();`);

  // Binding handlers. Without these the wrapper is write-only: Svelte's copy
  // of the prop never updates, so the next unrelated re-render re-sets the
  // stale value onto the element and silently reverts the user's input.
  const handlers = new Map();
  if (bindings.size > 0) {
    const used = new Set();
    lines.push('');
    lines.push('  // Two-way binding — mirror the event detail back onto the prop, then');
    lines.push('  // forward to the consumer\'s own handler, which {...rest} would otherwise');
    lines.push('  // have attached. These are declared after {...rest} below so they win.');
    for (const [event, props] of bindings) {
      const fn = handlerName(event, used, '__on');
      handlers.set(event, fn);
      lines.push(`  function ${fn}(e: Event) {`);
      lines.push(`    const detail = (e as CustomEvent).detail as Record<string, unknown> | null;`);
      lines.push('    if (detail) {');
      for (const name of props) {
        lines.push(`      if ('${name}' in detail) ${locals.get(name)} = detail.${name} as ${propTypes.get(name)};`);
      }
      lines.push('    }');
      lines.push(`    (rest['on${event}'] as ((e: Event) => void) | undefined)?.(e);`);
      lines.push('  }');
    }
  }

  lines.push('</script>');
  lines.push('');

  // Template
  // Shorthand `{name}` unless the local was renamed — `{forProp}` would bind
  // the wrong attribute, so those spell out `for={forProp}`.
  const attrs = meta.props
    .map((p) => (renamed(p.name) ? `${p.name}={${locals.get(p.name)}}` : `{${p.name}}`))
    .join(' ');
  const attrStr = attrs ? ` ${attrs} {...rest}` : ' {...rest}';

  if (handlers.size === 0) {
    lines.push(`<${meta.tag}${attrStr}>`);
  } else {
    lines.push(`<${meta.tag}${attrStr}`);
    for (const [event, fn] of handlers) {
      lines.push(`  on${event}={${fn}}`);
    }
    lines.push('>');
  }
  lines.push(`  {@render children?.()}`);
  lines.push(`</${meta.tag}>`);
  lines.push('');

  writeFileSync(outPath, lines.join('\n'));
  return { path: outPath, written: true };
}
