/**
 * Generates Vue 3 SFC (.vue) files from ComponentMeta.
 * Uses defineProps with TS generics and defineEmits for type safety.
 */

import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { isPrismGenerated } from './header.js';
import { tsType } from './types.js';
import { deriveBindings, boundPropNames, handlerName } from './bindings.js';

const HEADER = '<!-- Auto-generated by @arclux/prism — do not edit manually -->';

/**
 * Format a default value for Vue's withDefaults().
 */
function vueDefault(prop) {
  if (!prop.default) return undefined;
  const val = prop.default;
  // Strip quotes for string literals — withDefaults uses JS values
  if (val.startsWith("'") || val.startsWith('"')) return val;
  if (val === 'true' || val === 'false') return val;
  if (!isNaN(Number(val))) return val;
  // Arrays/objects need factory functions
  if (val.startsWith('[') || val.startsWith('{')) return `() => (${val})`;
  return `'${val}'`;
}

/**
 * Generate a Vue 3 SFC .vue file for a component.
 * @param {import('./parser.js').ComponentMeta} meta
 * @param {object} config - vue config section
 * @param {string} root - project root
 * @returns {{ path: string, written: boolean }}
 */
export function generateVue(meta, config, root) {
  const outDir = join(root, config.outDir, meta.tier);
  const outPath = join(outDir, `${meta.pascalName}.vue`);

  // Safety: never overwrite files without our header
  if (existsSync(outPath)) {
    const existing = readFileSync(outPath, 'utf-8');
    if (!isPrismGenerated(existing)) {
      return { path: outPath, written: false };
    }
  }

  mkdirSync(outDir, { recursive: true });

  const wcImport = config.wcPackage || `@${config.prefix}/${config.prefix}-ui`;
  // Per-component register subpath — registers only this element (guarded define)
  const registerImport = `${wcImport}/${meta.tag.slice(config.prefix.length + 1)}`;
  const lines = [HEADER];

  // <script setup lang="ts">
  lines.push('<script setup lang="ts">');
  lines.push(`import '${registerImport}';`);
  lines.push('');
  lines.push(`defineOptions({ name: '${meta.pascalName}' });`);
  lines.push('');

  // Props
  const hasProps = meta.props.length > 0;
  const hasDefaults = meta.props.some((p) => p.default);

  if (hasProps) {
    const propsBlock = meta.props
      .map((p) => `  ${p.name}?: ${tsType(p)};`)
      .join('\n');

    // The props object is captured rather than left unassigned so the template
    // can read every prop through it. A prop named after a reserved word
    // (`for`, `class`, `default`) is illegal as a bare identifier in a template
    // expression but fine as a property access, so `props.for` retires the
    // whole class of problem instead of special-casing individual names.
    if (hasDefaults) {
      lines.push(`const props = withDefaults(defineProps<{`);
      lines.push(propsBlock);
      lines.push(`}>(), {`);
      for (const prop of meta.props) {
        const def = vueDefault(prop);
        if (def !== undefined) {
          lines.push(`  ${prop.name}: ${def},`);
        }
      }
      lines.push(`});`);
    } else {
      lines.push(`const props = defineProps<{`);
      lines.push(propsBlock);
      lines.push(`}>();`);
    }
  }

  // Two-way bindings, derived from event detail keys that match prop names.
  // Without the matching `update:x` emit, `v-model:x` on the wrapper silently
  // does nothing and every re-render re-sets the stale prop onto the element.
  const twoWay = deriveBindings(meta, config);
  const boundProps = boundPropNames(twoWay);
  const propTypes = new Map(meta.props.map((p) => [p.name, tsType(p)]));

  // Events — capture the emit function so template listeners can relay the
  // underlying custom events. Declaring these in defineEmits also removes them
  // from Vue's native listener fallthrough, so they MUST be wired explicitly in
  // the template below or the parent's @arc-click handler would never fire.
  const hasEvents = meta.events.length > 0;
  if (hasEvents) {
    lines.push('');
    lines.push(`const emit = defineEmits<{`);
    for (const event of meta.events) {
      lines.push(`  '${event}': [event: CustomEvent];`);
    }
    // `update:x` is what v-model:x listens for.
    for (const prop of meta.props) {
      if (boundProps.has(prop.name)) {
        lines.push(`  'update:${prop.name}': [value: ${tsType(prop)}];`);
      }
    }
    lines.push(`}>();`);
  }

  // Named handlers for events that write a prop back. Declared here rather
  // than inline in the template so the `in` guard is readable.
  const handlers = new Map();
  if (twoWay.size > 0) {
    // Seed with prop names — and `props` itself — so a handler can never
    // shadow either in the template.
    const used = new Set([...meta.props.map((p) => p.name), 'props']);
    lines.push('');
    for (const [event, props] of twoWay) {
      const fn = handlerName(event, used);
      handlers.set(event, fn);
      lines.push(`function ${fn}(payload: CustomEvent) {`);
      lines.push(`  emit('${event}', payload);`);
      lines.push(`  const detail = payload.detail as Record<string, unknown> | null;`);
      lines.push('  if (detail) {');
      for (const name of props) {
        lines.push(`    if ('${name}' in detail) emit('update:${name}', detail.${name} as ${propTypes.get(name)});`);
      }
      lines.push('  }');
      lines.push('}');
    }
  }

  lines.push('</script>');
  lines.push('');

  // <template>
  lines.push('<template>');

  // Build attribute and event bindings on the wrapped element.
  const bindings = meta.props.map((p) => `    :${p.name}="props.${p.name}"`);
  const eventBindings = meta.events.map((e) => (
    handlers.has(e)
      ? `    @${e}="${handlers.get(e)}"`
      : `    @${e}="(payload: CustomEvent) => emit('${e}', payload)"`
  ));
  const allBindings = [...bindings, ...eventBindings];

  if (allBindings.length > 0) {
    lines.push(`  <${meta.tag}`);
    lines.push(allBindings.join('\n'));
    lines.push(`  >`);
  } else {
    lines.push(`  <${meta.tag}>`);
  }

  lines.push(`    <slot />`);
  lines.push(`  </${meta.tag}>`);
  lines.push('</template>');
  lines.push('');

  writeFileSync(outPath, lines.join('\n'));
  return { path: outPath, written: true };
}
