/**
 * Checks made *before* anything is written.
 *
 * `verify.js` reads output back after a run — the right shape for a generator
 * bug, where a wrong file can be regenerated correctly. It is the wrong shape
 * for the most destructive failure prism has: **an older prism does not error,
 * it reverts.** Prism rewrites every file it owns from whatever version is
 * installed, so regenerating over a newer version's output silently undoes it,
 * and the only signal is a large diff in generated files nobody reads.
 *
 * The version stamp (see header.js) makes that visible, and the CLI's per-file
 * check reports it — but only while overwriting, and the finding clears itself
 * on the next run once the files carry the older stamp. So the same stamp is
 * read here first, across the whole output tree, before a single write. Under
 * `--strict` that turns a revert into a run that refuses to start.
 */

import { openSync, readSync, closeSync, readdirSync, existsSync, statSync } from 'node:fs';
import { Buffer } from 'node:buffer';
import { join } from 'node:path';
import { VERSION, isPrismGenerated, generatedVersion, compareVersions } from './generators/header.js';

/**
 * How much of each file to read — the same window `isPrismGenerated` inspects.
 * Reading whole files to look at their first line would make a pre-flight over
 * a large tree cost more than the generate it precedes.
 */
const HEAD_BYTES = 300;

/** The first `HEAD_BYTES` of a file, or '' if it can't be read. */
function head(path) {
  let fd;
  try {
    fd = openSync(path, 'r');
    const buf = Buffer.alloc(HEAD_BYTES);
    const read = readSync(fd, buf, 0, HEAD_BYTES, 0);
    return buf.toString('utf-8', 0, read);
  } catch {
    return '';
  } finally {
    if (fd !== undefined) closeSync(fd);
  }
}

/**
 * Every directory prism writes generated files into.
 *
 * Deliberately not recursive below the tiers, matching what the generators
 * actually do: a framework writes `outDir/<tier>/Name.ext`, and CSS, HTML and
 * the JSX declarations are flat. Walking arbitrarily deep would start reading a
 * consumer's own source.
 */
function outputDirs(config, root) {
  const dirs = new Set();
  for (const key of ['react', 'vue', 'svelte', 'angular', 'solid', 'preact']) {
    if (!config[key]) continue;
    dirs.add(join(root, config[key].outDir));
    for (const tier of config.tiers) dirs.add(join(root, config[key].outDir, tier));
  }
  for (const key of ['css', 'html']) {
    if (config[key]) dirs.add(join(root, config[key].outDir));
  }
  if (config.jsxTypes) dirs.add(join(root, config.jsxTypes.outDir));
  return [...dirs];
}

/**
 * Find generated output written by a *newer* prism than the one about to run.
 *
 * MUST be called before any generator writes, and only in the modes that rewrite
 * the whole tree — a full run, or a watcher's initial pass. Single-file mode
 * doesn't get one: it rewrites one file, so the per-file check covers it, and a
 * whole-tree scan there would report on files the run will never touch.
 *
 * @param {object} config - normalized config
 * @param {string} root - project root
 * @returns {{ newer: Array<{ path: string, version: string }>, scanned: number,
 *   highest: string|null }}
 */
export function scanForNewerOutput(config, root) {
  const newer = [];
  let scanned = 0;
  let highest = null;

  for (const dir of outputDirs(config, root)) {
    if (!existsSync(dir)) continue;
    for (const name of readdirSync(dir)) {
      const path = join(dir, name);
      try {
        if (!statSync(path).isFile()) continue;
      } catch {
        continue;
      }
      const text = head(path);
      if (!isPrismGenerated(text)) continue;
      scanned++;
      const version = generatedVersion(text);
      if (!version || compareVersions(version, VERSION) <= 0) continue;
      newer.push({ path, version });
      if (!highest || compareVersions(version, highest) > 0) highest = version;
    }
  }

  return { newer, scanned, highest };
}

/**
 * The finding for one file the run is about to revert. Worded in the
 * conditional — "would revert" — because unlike the per-file check, nothing
 * has been written yet.
 *
 * @param {{ path: string, version: string }} entry
 * @param {string} file - the path, relative to the project root
 * @returns {import('./parser.js').Diagnostic}
 */
export function downgradeFinding(entry, file) {
  return {
    code: 'generator-downgrade',
    message:
      `${file} was generated by prism ${entry.version}, and this run is ${VERSION}. ` +
      'Regenerating would rewrite it from the older generator — a downgrade does not fail, ' +
      `it reverts. Install ${entry.version} or later, or reset this file to its committed state ` +
      'if the output is what moved rather than the generator.',
    file: entry.path,
    priorVersion: entry.version,
    version: VERSION,
  };
}

/**
 * The block printed when a downgrade is found. One aggregate rather than a line
 * per file — the per-file findings carry the list, and what someone needs here
 * is the count, the two versions, and whether the tree was touched yet.
 *
 * @param {ReturnType<typeof scanForNewerOutput>} scan
 * @param {boolean} aborting - whether the run is stopping here
 * @returns {string}
 */
export function describeDowngrade(scan, aborting) {
  const n = scan.newer.length;
  return (
    `\nprism: ${n} generated file${n === 1 ? '' : 's'} on disk ${n === 1 ? 'was' : 'were'} ` +
    `written by @arclux/prism ${scan.highest}, and this run is ${VERSION}.\n` +
    `  An older generator does not error — it rewrites, so regenerating reverts ` +
    `${n === 1 ? 'it' : 'all of them'} to what\n  this version emits, and the only trace is a large diff in files nobody reads.\n` +
    (aborting
      ? '  Nothing has been written. Two ways out, depending on which side moved:\n' +
        `    install @arclux/prism ${scan.highest} or later, if the generator is what went backwards;\n` +
        '    or reset the generated tree to its committed state, if the output is what came forward.\n' +
        '  Dropping --strict regenerates over it anyway.'
      : `  Install ${scan.highest} or later if the generator is what went backwards, or reset the\n` +
        '  generated tree if the output is. Either way, check the diff before committing.')
  );
}
